### ISSUE TITLE
Can add-ons which are still under development, but present on the official web site be included in the data base?

### ISSUE THREAD

**Issue by lukaszgo1** [nvdaaddons/nvdaaddons.github.io#3]
I would like to allow users of my add-on for Becky! Internet Mail to receive updates via add-on updater. The add-on has only development releases for now, and I am wondering if dev only add-ons can be included in the json data base. cc @XLTechie  for eventual comments as you're responsible for the database nova days.

**Comment by XLTechie** [comment]
As I understand it, if the add-on is installed, and then you configure Add-on 
Updater to prefer development releases for that add-on, they will still be 
pulled even though they are not in the database.

In other words: @josephsl is still using the classical update code for dev 
releases in Updater.

Is this not working?

**Comment by lukaszgo1** [comment]
> As I understand it, if the add-on is installed, and then you configure Add-on Updater to prefer development releases for that add-on, they will still be pulled even though they are not in the database. In other words: @josephsl is still using the classical update code for dev releases in Updater. Is this not working?


No, it is not. Also looking at the addon updater's code I don't think this is true any longer.

**Comment by XLTechie** [comment]
> No, it is not. Also looking at the addon updater's code I don't think this is true any longer.

I will investigate. However, note that I do not maintain Updater. Any fix will 
have to await @josephsl's return in July.

There has to be some reason why he kept dev versions out of the JSON database, 
and without knowing what that is I am hesitant to just add them.

**Comment by XLTechie** [comment]
What specific add-on has prompted this question?
What version should be the latest, and where can I get an older version?

**Comment by XLTechie** [comment]
Never mind. I found 
https://github.com/lukaszgo1/Becky/releases/download/V0.3-dev/Becky-0.3-dev.nvda-addon
for current, and 
https://github.com/lukaszgo1/Becky/releases/download/V0.2-dev/Becky-0.2-dev.nvda-addon
for previous.

**Comment by XLTechie** [comment]
The issue appears to be that Updater is not noticing dev versions of add-ons 
that don't have stable versions as well. That is a rare situation, which is 
probably why it was not previously discovered.
I'll take it up with @josephsl when he returns.

I have applied what is likely a temporary solution, covering the case of Becky. 
It should be updating now.

Speaking of Becky, your summary is:

Becky accessibilit enhancements

I believe that should be:

Becky accessibility enhancements

**Comment by lukaszgo1** [comment]
> Speaking of Becky, your summary is: Becky accessibilit enhancements I believe that should be: Becky accessibility enhancements


I've fixed this for version 0.3. Are you sure you haven't tested with the older build?

**Comment by XLTechie** [comment]
I'm sorry, you're right. I had them both downloaded for testing. Thought I was 
in the new manifest but must have been in the old.

**Comment by josephsl** [comment]
Hi all,

I I'm back, although I won't return to significant coding activities until July.

Add-on Updater relies on community add-ons database to obtain download links. Even if the JSON from this repo is consulted for compatibility data, if an add-on is not registered on add-on files repository, Add-on Updater will not be able to compare versions. Therefore, what you are seeing with Becky! is actually the intended behavior - if I'm reading NVDA Add-ons list archive and add-on files repo correctly, Becky! add-on dev version was approved for distribution a few days ago, and this repo's JSON file had an entry for Becky! add-on before that. Therefore since add-on files database (get.php) did not have Becky! add-on prior to distribution, it makes sense that Add-on Updater will not offer the dev version of this add-on. Ultimately, it is up to NV Access to approve add-on files pull requests for new add-ons, as the JSON file hosted here provides compatibility statements and a mapping between add-on identifier reported by NVDA and the key stored on get.php.

Hope this clarifies a lot (after reviewing this issue, I realized that I need to sit down and write Add-on Updater internals someday...). Thanks.

**Comment by XLTechie** [comment]
@josephsl

I believe you have misunderstood the timeline.

First, the PR linking to the dev version of Becky was submitted to addonFiles.

Second, it was merged.

Third, after it was merged, Updater did not offer to update installed versions.

Fourth, only then did I add an entry to the JSON database, which allowed Updater 
to suggest updates to the installed dev versions.

See josephsl/addonUpdater#10 for an explication of the difficulty and 
its resolution, along with potential future options.

This is more of an undocumented use case rather than unintended behavior.

The applicable rule seems to be: dev add-ons which do not have an associated 
stable version, must be given a JSON database entry as if they did have a stable 
version.

**Comment by josephsl** [comment]
Hi, I see, thanks for clarifying.
